// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq3YuQRMGaja5LMuSbsP9AytM7SHBZ7g4',
    appId: '1:868741922083:web:a6e0985ba876aec10c2096',
    messagingSenderId: '868741922083',
    projectId: 'torrefacteurk-524a6',
    authDomain: 'torrefacteurk-524a6.firebaseapp.com',
    databaseURL: 'https://torrefacteurk-524a6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'torrefacteurk-524a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBILeclhvlY2586-Y1O8xFZnWWoAXgt0s',
    appId: '1:868741922083:android:7cea3e07f7650daf0c2096',
    messagingSenderId: '868741922083',
    projectId: 'torrefacteurk-524a6',
    databaseURL: 'https://torrefacteurk-524a6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'torrefacteurk-524a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkUQOYAkfX02xHKcTwP8VzN6sxXpVwYG0',
    appId: '1:868741922083:ios:0c0054978f6354d90c2096',
    messagingSenderId: '868741922083',
    projectId: 'torrefacteurk-524a6',
    databaseURL: 'https://torrefacteurk-524a6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'torrefacteurk-524a6.appspot.com',
    iosBundleId: 'com.example.torrefacteurk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkUQOYAkfX02xHKcTwP8VzN6sxXpVwYG0',
    appId: '1:868741922083:ios:783582a36adf3e340c2096',
    messagingSenderId: '868741922083',
    projectId: 'torrefacteurk-524a6',
    databaseURL: 'https://torrefacteurk-524a6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'torrefacteurk-524a6.appspot.com',
    iosBundleId: 'com.example.torrefacteurk.RunnerTests',
  );
}
